#!/bin/sh
#
# description: Apply Patch 6.1
#
mos=/usr/local/etc/mos

case "$1" in
  start)
	cp -a $mos/patch61/* /
	/sbin/depmod
	$mos/bin/pm remove patch61
	echo '324002_r6.1' > /etc/system_svn_version
	sync
	reboot
	;;
  stop|status|enable|disable)
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
