#!/bin/sh
#
# run script named autorun 
# on plugged drive
#

# check returned hotplug status
[ $1 -ne 0 ] && exit

# check action
[ "$ACTION" != 'add' ] && exit

s=$( echo "$DEVPATH" | sed -n 's/^.*\/\(.*\)$/\1/p' )
[ -z "$s" ] && exit

# save device
dev="$( cat /proc/mounts | grep ' /tmp/usbmounts/'$s' ' | cut -d ' ' -f 1 )"

sleep 5

# autorun
s="$( cat /proc/mounts | grep -E '^'$dev | cut -d ' ' -f 2 )"
if [ -n "$s" ] ; then
	if [ -f $s/autorun ] ; then
		cr=$( printf "\r" )
		sed "s/$cr//" $s/autorun > /tmp/autorun
		chmod +x /tmp/autorun
		/tmp/autorun
		rm /tmp/autorun
	fi
fi
	