#!/bin/sh
#
# description: Enable and disable Rutor
#
etc=/usr/local/etc
mos=$etc/mos/rutor
ims=/tmp/app/ims

case "$1" in
  start)
	cp -a $mos/btadd.cgi /tmp/www/cgi-bin/
	mkdir -p $ims
	cp -a $mos/ims/ims_rutor.png $ims/
	cp -a $mos/ims/rutor-dynamicPopup.rss $ims/
	ln -s $mos/ims/image-rutor/ $ims/image-rutor
	;;

  stop)
	rm -f $ims/ims_rutor.png
	rm -f $ims/rutor-dynamicPopup.rss
	rm -f $ims/image-rutor
	rm -f /tmp/www/cgi-bin/btadd.cgi
	;;

  status)
	if [ -f $ims/ims_rutor.png ]
	then echo "rutor running"
	else echo "rutor stopped"
	fi
	;;
  enable|disable)
	;;

  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
