#!/bin/sh
#
# description: Enable and disable IRFake
#
etc=/usr/local/etc
mos=$etc/mos/irfake
rc=$etc/rcS

case "$1" in
  start|stop|status)
	;;
  enable)
	echo "Enabling IRFake..."
	#copy files
	cp -a $mos $etc/

	# patch rcS
	sed -i '/# irfake patch/{N;N;N;d}' /usr/local/etc/rcS
	sed -i '
/ln -s \/dev\/cdroms\/cdrom0 \/dev\/cdrom0/i\
# irfake patch\
/sbin/insmod '$etc'/irfake/venus_ir_new.ko\
'$etc'/irfake/irfake4 -R -f '$etc'/irfake/irfake.conf&\
#\

' /usr/local/etc/rcS
	echo "Please, reboot device!"
	;;

  disable)
	echo "Disabling IRFake..."
	sed -i '/# irfake patch/{N;N;N;N;d}' /usr/local/etc/rcS
	killall irfake4
	echo "Please, reboot device!"
	;;
  copy)
	cp $etc/irfake/irfake.conf $mos/irfake.conf
	;;

  save)
	killall irfake4
	cp $mos/irfake.conf $etc/irfake/irfake.conf
	$etc/irfake/irfake4 -R -f $etc/irfake/irfake.conf >/dev/null 2>&1 &
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
