#!/bin/sh
#
# description: Enable and disable pathed RootApp
#
etc=/usr/local/etc
mos=$etc/mos

case "$1" in
  start | stop | status)
	;;

  enable)
	echo "Enabling pathed RootApp..."

	#check for already enabled
	if [ ! -f /usr/local/etc/RootApp ] ; then

		# Copying RootApp
		cp -af $mos/bin/RootApp /usr/local/etc/

		# Patching rcS
		sed -i 's/^\(.*\)\.\/RootApp DvdPlayer\(.*\)$/\1\/usr\/local\/etc\/RootApp DvdPlayer\2/' $etc/rcS

		# adding RootApp scripts
		cp -a $mos/etc/rc.suspend $etc/
		cp -a $mos/etc/rc.wakeup $etc/
	fi
	echo "Patched RootApp enabled"
	echo "Please, reboot device!"
	;;

  disable)
	echo "Disabling patched RootApp..."
	#check for already disabled
	if [ -f /usr/local/etc/RootApp ] ; then

		# Stopping GUI
		stopall
		killall -9 RootApp
		sleep 2

		# Patching rcS
		sed -i 's/^\(.*\)\/usr\/local\/etc\/RootApp DvdPlayer\(.*\)/\1\.\/RootApp DvdPlayer\2/' $etc/rcS

		# Removing files
		rm -f /usr/local/etc/RootApp

		# remove RootApp scripts
		rm -f $etc/rc.wakeup
		rm -f $etc/rc.suspend

		echo "Patched RootApp disabled"
		echo "Please, reboot device!"
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
