#!/bin/sh
#
# Check for install:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#
rc=/usr/local/etc/rcS

[ -e /tmp/ir ] && exit 1
[ -f $rc ] || exit 1
grep -q 'RootApp DvdPlayer' $rc || exit 1

exit 0
