#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010-2011  Serge A. Timchenko
#   Copyright (C) 2011  nnb
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#


local DATAPATH=$BASEPATH/app/zoomby

local PAGEFILE=$CACHEPATH/zoomby.page
local PAGEXML=$CACHEPATH/zoomby.xml

$MSDL -q -o "$PAGEFILE" -p http "$arg_opt"
if [ -f "$PAGEFILE" ]; then
   local pages=$(awk '/window.location.href=.\?/{len = split($0, arr, /window.location.href=.\?page=/); match(arr[len], /^([0-9]+)/, a); pages=a[1];}END {print pages;}' $PAGEFILE)

   if [ "$pages" = "" ]; then
    pages=1
   fi

cat > $PAGEXML <<EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
 <channel>
  <title>ZOOMBY.RU</title>
  <link>http://zoomby.ru</link>
  <description>ZOOMBY.RU</description>
  <language>ru</language>
  <pages>$pages</pages>
EOF

   if [ -x $XSLTPROC ]; then
    if echo $arg_opt | grep -qs 'genres\|collections' ; then
     $XSLTPROC --encoding utf-8 --html $DATAPATH/music_videos.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
    elif echo $arg_opt | grep -qs 'search?q=' ; then
     $XSLTPROC --encoding utf-8 --html $DATAPATH/music_videos.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
    else
     $XSLTPROC --encoding utf-8 --html $DATAPATH/music_videos_old.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
    fi
   fi

cat >> $PAGEXML <<EOF
 </channel>
</rss>
EOF

   rm -f $PAGEFILE
fi

[ -f "$PAGEXML" ] && printContent "text/xml" $PAGEXML

