#!/bin/sh
#
# Check for install libgcc_s:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#

f=1
while true; do
	lib=$( echo $LD_LIBRARY_PATH: | cut -d':' -f $f )
	[ -z "$lib" ] && exit 0
	if [ -e $lib/libgcc_s.so ] ; then
		echo $( realpath $lib/libgcc_s.so ) | grep -q uClibc && exit 0
		exit 2
	fi
	let f+=1
done
