#!/bin/sh
#
# description: Starts and stops the core of moServices
#

# Replace IMS menu to moMenu
mosReplace=yes

etc=/usr/local/etc
mos=$etc/mos

dvs=$etc/dvdplayer
spa=$dvs/savedrss/scripts

menu=$mos/www/modules/core/def_rss.php
more=$mos/www/modules/core/rss

dst='/tmp/www'
#
# -------------------------------------
doXtreamer()
{
	case "$1" in
	  start)
		# present hdds ?
		if ! $mos/bin/wait_mount ; then
			# present xTreamering ?
			xtr='';
			for i in $( ls /tmp/usbmounts ) ; do
				if [ -f /tmp/usbmounts/$i/scripts/Xtreamering/index.php ] ; then
					xtr=/tmp/usbmounts/$i/scripts/Xtreamering
					mount -o remount,rw /tmp/usbmounts/$i
					break
				fi
			done
			if [ -n "$xtr" ] ; then
				[ ! -f $xtr/index_orig.php ] && mv -f $xtr/index.php $xtr/index_orig.php

				# redirect to rss_menu
				echo '<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: http://".$_SERVER["HTTP_HOST"]."/mos/?page=rss_menu");
exit();
?>' > $xtr/index.php

				# add orig menu to rss_menu
				grep -q 'Xtreamering/index_orig.php' $menu || sed -i '
/\$nav_rss\["aaa"\] = array/{N;N;N;N;N;N;d}
/\?>/i\
$nav_rss["aaa"] = array (\
	"module"=> "core",\
	"rss"	=> "http://127.0.0.1/media/'$i'/scripts/Xtreamering/index_orig.php",\
	"icon"  => "rss/images/xTreamering.png",\
	"title" => "xTreamering"\
);\

' $menu
			fi
		fi
		# set cmdset
		grep -Eq 'commands.*xtreamer' $mos/etc/core.ini || sed -ir 's/^([ \t]*commands[ \t]*=[ \t]*).*$/\1xtreamer/' $mos/etc/core.ini
		;;
	  stop)
		# present xTreamering ?
		xtr='';
		for i in $( ls /tmp/usbmounts ) ; do
			if [ -f /tmp/usbmounts/$i/scripts/Xtreamering/index.php ] ; then
				xtr=/tmp/usbmounts/$i/scripts/Xtreamering
				break
			fi
		done

		[ -n $xtr ] && \
		[ -f $xtr/index.php ] && \
		[ -f $xtr/index_orig.php ] && \
		mv -f $xtr/index_orig.php $xtr/index.php
		;;
	  *)
		;;
	esac
	dst='/sbin/www/mos'
}
#
# =====================================
case "$1" in
  start)
	if [ -d /sbin/www ] ; then

		doXtreamer start
	else
		# Standard FW

		# unicgi patch
		uni=''
		for i in $etc /usr/local/bin /usr/local/bin/Resource ; do
			if [ -f $i/package/script/unicgi ] ; then
				if grep -Eq 'rm -rf /var/www$' $i/package/script/unicgi ; then
					uni="$( realpath $i/package/script/unicgi )"
					break
				fi
			fi
		done
		if [ -n "$uni" ] ; then
			mount -o bind $mos/etc/unicgi $uni
		fi

		# find and replace default IMS
		orig='/usr/local/bin/scripts/menu.rss'
		if [ "$mosReplace" == 'yes' ] ; then
			if [ -f $etc/menu_orig.rss ] ; then
				orig=$etc/menu_orig.rss
			else
				if [ -f $spa/menu.rss ] ; then

					if [ -L $spa/menu.rss ] ; then
						if ! [ "$( readlink $spa/menu.rss )" == "$more/moMenu.rss" ] ; then
							ln -s $( readlink $spa/menu.rss ) $etc/menu_orig.rss
							rm -f $spa/menu.rss
							orig=$etc/menu_orig.rss
						fi
					else
						mv -f $spa/menu.rss $etc/menu_orig.rss
						orig=$etc/menu_orig.rss
					fi
				fi
			fi
			mkdir -p $spa

			[ -f $spa/menu.rss ] && \
			[ "$( readlink $spa/menu.rss )" != "$more/moMenu.rss" ] && \
			rm -f $spa/menu.rss

			[ -f $spa/menu.rss ] || ln -s $more/moMenu.rss $spa/menu.rss

		else
			if [ -f $spa/menu.rss ] ; then

				if [ -L $spa/menu.rss ] ; then
					if [ "$( readlink $spa/menu.rss )" == "$more/moMenu.rss" ] ; then
						rm -f $spa/menu.rss
						[ -f $etc/menu_orig.rss ] && mv $etc/menu_orig.rss $spa/menu.rss
					fi
				fi
				orig=$spa/menu.rss
			fi
		fi

		# Asus HD2 patch
		nas=/usr/local/bin/scripts/nas/nasSetup.rss
		if [ -L $nas ] ; then
			[ ! -f $nas.orig ] && mv -f $nas $nas.orig
			[ -f $nas ] && [ "$( readlink $spa/menu.rss )" != "$more/moServices.rss" ] && rm -f $nas
			[ ! -f $nas ] && ln -s $more/moServices.rss $nas
		else
			if [ -f $nas ] ; then
				mount | grep -q $nas || mount -o bind $more/moServices.rss $nas
			fi
		fi

		# add orig menu to rss_menu
		grep -q "$orig" $menu || sed -i '
/\$nav_rss\["aaa"\] = array/{N;N;N;N;N;N;d}
/\?>/i\
$nav_rss["aaa"] = array (\
	"module"=> "core",\
	"rss"	=> "rss_file://'$orig'",\
	"icon"  => "rss/images/OnlineMedia.png",\
	"title" => "Online Media"\
);\

' $menu
		# set cmdset
		grep -Eq 'commands.*sdk' $mos/etc/core.ini || sed -ir 's/^([ \t]*commands[ \t]*=[ \t]*).*$/\1sdk/' $mos/etc/core.ini

		dst='/tmp/www'
	fi

	# copy www files
	[ ! -d $dst ] && mkdir $dst
	cp -a $mos/www/index.php $dst
	cp -a $mos/www/favicon.ico $dst
	[ -e $dst/modules ] && rm -f $dst/modules
	ln -s $mos/www/modules/ $dst/modules
	sync
	;;

  stop)
	if [ -d /sbin/www ] ; then

		doXtreamer stop
	else
		# Standard FW

		# Asus HD2 patch
		nas=/usr/local/bin/scripts/nas/nasSetup.rss
		if ! [ -L $nas ] ; then
			mount | grep -q $nas && umount $nas
		fi

		dst='/tmp/www'
	fi
	rm -f $dst/index.php
	rm -f $dst/favicon.ico
	rm -f $dst/modules
	;;

  status | enable | disable)
	;;
  *)
	echo "Usage: $0 {start|stop|enable|disable|status}"
	;;
esac

exit $?
