#!/bin/sh
#
etc=/usr/local/etc
mos=$etc/mos

# enable start script for check
chmod +x $mos/etc/init/S47mosondrive

#check flag "moS on drive"
if [ -f $etc/.mosOnDrive ] ; then

	# already mounted?

	m=''
	s="$( mount | grep $mos | cut -d ' ' -f 1 )"
	for i in $s ; do
		# check for root mounted
		[ "$i" != '/dev/root' ] && m=$i
	done

	if [ -z "$m" ] ; then
		# wait for mount and
		# check the mos image or dir present
		disk=
		n=60
		while [ $n -ne 0 ] ; do
			s="$( mount | grep /dev/scsi/host | cut -d ' ' -f 3 )"
			if [ -n "$s" ] ; then
				for i in $s ; do
					if [ -e $i/.mos ] ; then
						disk=$i
						break
					fi
				done
				[ -n "$disk" ] && break
			fi
			let n-=1
			sleep 5
		done
		if [ -n "$disk" ] ; then

			mount -o remount,rw $disk

			# check to image or dir
			if [ -d $disk/.mos ] ; then
				mount $disk/.mos $mos
			else
				mount -o loop,rw $disk/.mos $mos
			fi
			sync
		fi
	fi
fi

if [ -f $mos/services_orig ] ; then
	exec $mos/services_orig $1
else
	exec $mos/services $1
fi
