#!/bin/sh
#
# description: Enable and disable pathed RootApp
#
etc=/usr/local/etc
mos=$etc/mos

case "$1" in
  start | stop | status)
	;;

  enable)
	echo "Enabling pathed RootApp..."

	#check for already enabled
	if [ ! -f /usr/local/etc/RootApp ] ; then

		# Copying RootApp
		cp -af $mos/bin/RootApp /usr/local/etc/

		# Patching rcS
		sed -ri 's!^(.*?)\.(/RootApp DvdPlayer.*)$!\1'$etc'\2!' $etc/rcS

		# adding RootApp scripts
		cp -a $mos/etc/rc.suspend $etc/
		cp -a $mos/etc/rc.wakeup $etc/

		echo "Patched RootApp enabled"
		echo "Please, reboot device!"
	fi
	;;

  disable)
	echo "Disabling patched RootApp..."
	#check for already disabled
	if [ -f /usr/local/etc/RootApp ] ; then

		# Stopping GUI
		stopall

		# Patching rcS
		sed -ri 's!^(.*)'$etc'(/RootApp DvdPlayer.*)$!\1.\2!' $etc/rcS

		# Removing files
		rm -f /usr/local/etc/RootApp

		# remove RootApp scripts
		rm -f $etc/rc.wakeup
		rm -f $etc/rc.suspend

		echo "Patched RootApp disabled"
		echo "Please, reboot device!"
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
