#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/music_ivi
cd $DATAPATH

local PAGEFILE=$CACHEPATH/music_ivi.page
local CHANNELXML=$CACHEPATH/music_ivi.xml

local URL=${arg_opt:-'http://music.ivi.ru/videos/top/day/all/all/all/all/all/'}
local TYPE=$(echo $URL | awk '{match($0,/music\.ivi\.ru\/([^/]+)\//,arr);print arr[1];}')

echo "<channel>" > $CHANNELXML
echo "  <title>MUSIC.IVI.RU</title>"    >> $CHANNELXML
echo "  <link>$URL</link>"              >> $CHANNELXML
echo "  <description></description>"    >> $CHANNELXML

$MSDL -q -o "$PAGEFILE" -p http --useragent "$USERAGENT" "$URL"

if [ -f "$PAGEFILE" ]; then
  if [ "$(ls -s "$PAGEFILE" | awk '{print $1}')" != "0" ]; then
    [ -x $XSLTPROC ] && $XSLTPROC --encoding utf-8 --html --stringparam type "$TYPE" video_list.xslt "$PAGEFILE" 2>/dev/null | sed '1d' >> $CHANNELXML
  fi
  if [ "$TYPE" = "artist" ]; then
    if grep -qs 'id="showMoreVideos"' $PAGEFILE; then
        local artist_id=$(awk '/id="subscribe"/{match($0,/data="([^"]+)"/,arr);print arr[1];exit;}' $PAGEFILE)
        $MSDL -q -o - -p http --useragent "$USERAGENT" "http://music.ivi.ru/artist/showmore?artistId=${artist_id}" | sed -e '1i\<div class="artist-all-video">' -e '$a\</div>' > $PAGEFILE
        [ -x $XSLTPROC ] && $XSLTPROC --encoding utf-8 --html --stringparam type "$TYPE" video_list.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $CHANNELXML
    fi
  fi
  rm -f "$PAGEFILE"
fi

echo "</channel>" >> $CHANNELXML

printContent "application/xml" $CHANNELXML

