#!/bin/sh
#
# Check for install:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#

# check already patched
grep -Eq '/usr/local/etc/rc\.' /usr/local/bin/RootApp && exit 2
# check platform
s=$( cat /sys/realtek_boards/cpu_id | sed 's/^.*\(.\)$/\1/' )
[ "$s" == '2' ] || exit 1

exit 0
