#!/bin/sh

case "$1" in
  start)
	# Power ON, for ....

	# STANDBY_CMD_SYSTEM_ON
	echo -en '\xf0\xfe' >/dev/tts/1
	# STANDBY_CMD_MUTE_OFF
	echo -en '\xf9\xfe' >/dev/tts/1
	;;
  stop)
	# Power Off, for ....
	sync
	# STANDBY_CMD_SYSTEM_OFF
	echo -en '\xf5\xfe' >/dev/tts/1
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	;;
esac

exit $?
