#!/bin/sh
#
# remount plugged drive as rw
# and ufds filesystem as utf8
#

# check returned hotplug status
[ $1 -ne 0 ] && exit

# check action
[ "$ACTION" != 'add' ] && exit

s=$( echo "$DEVPATH" | sed -n 's/^.*\/\(.*\)$/\1/p' )
[ -z "$s" ] && exit

# save device
dev="$( cat /proc/mounts | grep /tmp/usbmounts/$s | cut -d ' ' -f 1 )"

#echo "saved device $dev" >>/tmp/remount.log

sleep 10

# remount device
s="$( cat /proc/mounts | grep -E '^'$dev )"
if [ -n "$s" ] ; then
	mt=$( echo $s | cut -d ' ' -f 2 )
	fs=$( echo $s | cut -d ' ' -f 3 )

	op=''
	[ "$fs" = 'ufsd' ] && op=' -o nls=utf8'

#	ps -w >>/tmp/remount.log
#	echo "mount $mt -o remount,rw $op" >>/tmp/remount.log
	mount $mt -o remount,rw $op >/dev/null 2>&1
fi
	