#!/bin/sh
#
# execute autorun script on plugged drives
#
hot=/usr/local/etc/mos/etc/hotplug/after/block/S12autorun

case "$1" in
  start)
	for i in /tmp/hdd/volumes/HDD* /tmp/hddmedia/* /tmp/usbmounts/sd* ; do
		[ -d $i ] || continue

		if [ -f $i/autorun ] ; then
			cr=$( printf "\r" )
			sed "s/$cr//" $i/autorun > /tmp/autorun
			chmod +x /tmp/autorun
			/tmp/autorun
			rm /tmp/autorun
		fi
	done
	;;

  enable)
	chmod +x $hot
	;;

  disable)
	chmod -x $hot
	;;

  stop|status)
	;;

  *)
	echo $"Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
