#!/bin/sh
#
# description: Starts and stops the Samba smbd daemon
#	       used to provide SMB network services.
#
etc=/usr/local/etc
bin=$etc/mos/bin
mos=$etc/mos/samba

stateSmb()
{
	ps | grep -q -e "$mos/[sS]mbd" -e "$mos/[nN]mbd" 
}



stopSmb()
{
	if stateSmb ; then
		echo 'Shutting down SMB services...'
		killall smbd
		echo 'Shutting down NMB services...'
		killall nmbd

		while stateSmb ; do sleep 1; done

		rm -Rf /tmp/smb
	fi
}

makeConfig()
{
	# making config
	mkdir -p /tmp/smb
	cp -a $mos/smb.conf /tmp/smb/smb.conf

	s=''
	for f in /tmp/ramfs/volumes/* ; do

		if [ -e $f ] && [ -L $f ] ; then
			n=$( basename $f | sed 's/://' )
			s=$( realpath $f )
			echo "
[$n]
path=$s
hide dot files=yes
guest ok=yes
writable=yes
browseable=yes
force create mode=0775
force directory mode=0775" >> /tmp/smb/smb.conf

		fi
	done
	[ -z "$s" ] && return 1
	return 0
}

case "$1" in
  start)

#	stopSmb

#	if ! makeConfig ; then
#		echo 'No samba shares.'
#		exit 1
#	fi

	makeConfig

	rm -Rf /tmp/smb/private
	cp -a $mos/private /tmp/smb/

	if ! stateSmb ; then

		$bin/wait_ip && exit 1

		echo 'Starting smbd services...'
		$mos/smbd -D -s /tmp/smb/smb.conf -l /tmp/smb >/dev/null 2>&1 &
	        echo 'Starting nmbd services...'
		$mos/nmbd -D -s /tmp/smb/smb.conf -l /tmp/smb >/dev/null 2>&1 &
	fi
	;;

  stop)
	stopSmb
	;;

  status)
	if stateSmb ; then
		echo 'SMB Service is running'
	else
		echo 'SMB Serice is stopped'
	fi
	;;

  reconfig)
	makeConfig
	;;

  enable | disable)
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
