#!/bin/sh
#
# description: Starts and stops the Samba smbd daemon
#	       used to provide SMB network services.
#
mos=/usr/local/etc/mos/samba

stopSmb()
{
	if ps | grep -q "$mos/[s]mbd" ; then
		echo 'Shutting down SMB services...'
		killall smbd
		echo 'Shutting down NMB services...'
		killall nmbd
		rm -Rf /tmp/smb
	fi
}

case "$1" in
  start|restart)

	stopSmb

	# have shares?
	s=''
	for f in /tmp/ramfs/volumes/* ; do
		if [ -e $f ] && [ -L $f ] ; then
			s=$f
			break
		fi
	done
	if [ -z "$s" ] ; then
		echo 'No samba shares.'
		exit 1
	fi

	# making config
	mkdir -p /tmp/smb
	cp -a $mos/smb.conf /tmp/smb/smb.conf

	for f in /tmp/ramfs/volumes/* ; do

		if [ -e $f ] && [ -L $f ] ; then
			n=$( basename $f | sed 's/://' )
			s=$( realpath $f )
			echo "
[$n]
path=$s
hide dot files=yes
guest ok=yes
writable=yes
browseable=yes
force create mode=0775
force directory mode=0775" >> /tmp/smb/smb.conf

		fi
	done

	rm -f /tmp/smb/private
	ln -s $mos/private/ /tmp/smb/private

	echo 'Starting smbd services...'
	$mos/smbd -D -s /tmp/smb/smb.conf -l /tmp/smb >/dev/null 2>&1 &
        echo 'Starting nmbd services...'
	$mos/nmbd -D -s /tmp/smb/smb.conf -l /tmp/smb >/dev/null 2>&1 &
	;;

  stop)
	stopSmb
	;;

  status)
	if ps | grep -q "$mos/[s]mbd" ; then
		echo 'SMB Service is running'
	else
		echo 'SMB Serice is stopped'
	fi
	;;

  enable | disable)
	;;
  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
