#!/bin/sh
#
# Check for install:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#

[ -f /usr/local/bin/home_menu/scripts/HomeMenu.rss ] && exit 0
[ -f /usr/local/bin/home_menu/scripts/HomeMenu_noDB.rss ] && exit 0
exit 1
