#!/bin/sh
#
# description: Starts and stops the UKRAINE ONLINE SERVICES
#
etc=/usr/local/etc
mos=$etc/mos/uaonline
dp=$etc/dvdplayer

cgi=/tmp/www/cgi-bin
[ -d '/sbin/www' ] && cgi='/sbin/www/cgi-bin'
                               	
case "$1" in
  start)
	echo "Starting uaonline..."
	[ ! -d $cgi ] && mkdir -p $cgi
	[ ! -e $cgi/scripts ] && ln -s $mos/ $cgi/scripts
	;;
  stop)
	echo "Stopping uaonline..."
	rm -f $cgi/scripts
	killall wget > /dev/null 2>&1
	;;

  status)
	if [ -e $cgi/scripts ] ; then
	  echo "uaonline is running"
	else
	  echo "uaonline is stopped"
	fi
	;;

  enable)
	;;

  disable)
	[ -f $dp/ex_search.dat    ] && rm $dp/ex_search.dat
	[ -f $dp/ex_lang.dat      ] && rm $dp/ex_lang.dat
	[ -f $dp/ex_settings.dat  ] && rm $dp/ex_settings.dat
	[ -f $dp/ex_bookmarks.dat ] && rm $dp/ex_bookmarks.dat
	;;

  *)
	echo "Usage: $0 {start|stop|status|enable|disable}"
	;;
esac

exit $?
